name: Scrape Parkleitsystem Gießen
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  schedule:
    - cron:  '10 * * * *'
defaults:
  run:
    working-directory: parkleitsystem/
jobs:
  scrape_and_save:
    runs-on: ubuntu-latest

    steps:
    - name: Run scraping script and save data
      run: |
        parkhouse_data=$(python3 scraping_parkleitsystem.py )
        filename="$(echo "$parkhouse_data" | jq -r .timestamp).json"
        echo $parkhouse_data > "data/$filename"