name: "Scrape Parkleitsystem Gießen"
on:
  schedule:
    - cron: '*/5 * * * *'
defaults:
  run:
    working-directory: parkleitsystem/
jobs:
  scrape_and_save:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .github
            parkleitsystem
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraping script and save data
        run: |
          parkhouse_data=$(python3 scraping_parkleitsystem.py)
          filename="$(echo "$parkhouse_data" | jq -r .timestamp).json"
          mkdir -p data
          touch data/$filename
          echo $parkhouse_data > "data/$filename"
      - name: Push changes to MASTER
        run: |
          git config user.name ${{ secrets.GIT_USERNAME }}
          git config user.email ${{ secrets.GIT_USEREMAIL }}
          git add .
          git commit -m 'Adding new parkhouse data'
          git push
