name: "Scrape Parkleitsystem Gießen"
on:
  schedule:
    - cron: '* * * * *'
defaults:
  run:
    working-directory: parkleitsystem/
jobs:
  scrape_and_save:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v3
    - name: Run scraping script and save data
      run: |
        parkhouse_data=$(python3 scraping_parkleitsystem.py )
        filename="$(echo "$parkhouse_data" | jq -r .timestamp).json"
        echo $parkhouse_data > "data/$filename"